apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-sockets
  namespace: data-dive
  labels:
    app: data-sockets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-sockets
  template:
    metadata:
      labels:
        app: data-sockets
    spec:
      containers:
      - name: data-sockets
        image: maheshmath/data-sockets:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: data-sockets
  namespace: data-dive
spec:
  type: NodePort
  selector:
    app: data-sockets
  ports:
    - port: 80
      targetPort: 8090
      nodePort: 30002