apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-sockets
  namespace: data-dive
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: maheshmath/data-sockets:latest
        ports:
        - containerPort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: data-sockets
  namespace: data-dive
spec:
  type: NodePort
  selector:
    app: data-sockets
  ports:
    - port: 30007
      targetPort: 30007
      nodePort: 30007